### ISSUE TITLE
[BUG] Estonian lemmatization never finishes

### ISSUE THREAD

**Issue by teemukolehmainen-howspace** [mikahama/uralicNLP#10]
**Describe the bug**
Estonian lemmatization does not return any results, the call gets stuck forever.

**To Reproduce**
1.  Build this dockerfile

```
FROM python:3.6.13-slim-buster
RUN pip install uralicNLP
RUN python -m uralicNLP.download --languages est
RUN python -c 'from uralicNLP import uralicApi; uralicApi.lemmatize("suvesse", "est")'
```
2. Build will fail because the last command never finishes

**Expected behavior**
A lemmatization result is returned shortly after entering the command.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: Buster
 - Python version 3.6.13

**Comment by mikahama** [comment]
Do python -m uralicNLP.download --languages est again, I updated the Estonian model... Please consider starring the repo
