### ISSUE TITLE
how to handle multiple generated forms

### ISSUE THREAD

**Issue by petri** [mikahama/uralicNLP#11]
I am trying to generate particular form for a set of words. Mostly everything produces good results, but sometimes there are two results, such as here:

```python
uralicApi.generate("rakennusteline+N+Pl+Ela", "fin")
[('rakennustelinehistä', 0.0), ('rakennustelineistä', 0.0)]
```

It appears the first result is in some local dialect, and the second form is more correct literary form. Why is this? Is there a way to limit the output to just literary form?

**Comment by mikahama** [comment]
Either open an issue in the Finnish transducer in https://github.com/giellalt/lang-fin or I am sure we can help through Rootroo for a fee https://rootroo.com
