### ISSUE TITLE
Method name typo: "descrpitive"

### ISSUE THREAD

**Issue by ogencoglu** [mikahama/uralicNLP#13]
A tiny detail.

`uralicApi.lemmatize`, `uralicApi.analyze` etc. seem to have the `descrpitive` field instead of `descriptive`. I guess it is a typo.

By the way is there any documentation of lemmatization behavior when `descrpitive` is `True` vs `False`? How about speed benchmarks?

**Comment by mikahama** [comment]
Thanks for this, I will change this in the future releases... And no, there is no documentation, basically the difference is that the transducers are compiled with different flags and what the transducers end up producing depends very much on the decisions of the authors of each language. You can try asking the maintainers of the languages you are interested in by opening an issue in one of the repositories: https://github.com/giellalt/ lang-ISOCODE.

**Comment by ogencoglu** [comment]
Thanks for the swift reply!
