### ISSUE TITLE
Randomness in lemmatization

### ISSUE THREAD

**Issue by ogencoglu** [mikahama/uralicNLP#14]
Lemmatization seem to give the order of the results in a non-deterministic manner **for each session run**.

**To Reproduce**

Creat the following `test.py` :
```
from uralicNLP import uralicApi
if __name__ == "__main__":
    for i in range(5):
        print(uralicApi.lemmatize(
            "liikkumisesta", language="fin", word_boundaries=False, descrpitive=True
        ))
```
and run several times with `python3.7 test.py` from the command line. **The order of the results are the same for each call of the function in the same session run but it varies between script runs.**

Results look like this e.g. for 4 runs:

```
user: ~/my/local/path $ python3.7 test.py 
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
user: ~/my/local/path $ python3.7 test.py 
['liikkua', 'liikkuminen']
['liikkua', 'liikkuminen']
['liikkua', 'liikkuminen']
['liikkua', 'liikkuminen']
['liikkua', 'liikkuminen']
user: ~/my/local/path $ python3.7 test.py 
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
user: ~/my/local/path $ python3.7 test.py 
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
['liikkuminen', 'liikkua']
```

**Expected behavior**
Deterministic results.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16
 - uralicNLP version: 1.2.3 (installed with pip)
 - HFST version: 3.15.0.0b0
 - Python version: 3.7

Language model downloaded with the command `python3.7 -m uralicNLP.download --languages fin`

Is there a way to fix the seed or make this work in a deterministic manner? Does the order of lemmas imply a probability ranking? If not, one can just sort the results to force the determinism I believe (assuming lemmatization results themselves are deterministic).

In any case, I think this should be documented somewhere in the readme.

**Comment by mikahama** [comment]
FSTs can give their output in a different order, it's a feature.
