### ISSUE TITLE
I can use get_all_forms for Finnish but cannot for Spanish.

### ISSUE THREAD

**Issue by za205** [mikahama/uralicNLP#16]
What could be the reason?

**Comment by mikahama** [comment]
Only Giella FSTs are supported by that method (the ones that have their tags separated by plus signs e.g. N+Sg+Nom. The Spanish transducer follows Apertium formatting and it's not supported.

**Comment by mikahama** [comment]
I fixed this in a new version. Now you can update UralicNLP and run:
```
from uralicNLP import uralicApi
uralicApi.get_all_forms("perro", "n", "spa")
>> [('perra:perro<n><f><sg>', 0.0), ('perras:perro<n><f><pl>', 0.0), ('perro:perro<n><m><sg>', 0.0), ('perros:perro<n><m><pl>', 0.0)]
```

**Comment by za205** [comment]
Thanks!!
