### ISSUE TITLE
[BUG] 🐛 🕷 🐞 wrong superlative for Finnish 'halpa'

### ISSUE THREAD

**Issue by doctorcolossus** [mikahama/uralicNLP#18]
`uralicNLP.generate(query="halpa+A+Superl+Sg+Nom", language="fin")`

expected: `[('halvin', 0.0)]`
actual: `[('halvoin', 0.0)]`

Seems like probably a giellalt issue, but do they even have an issue tracker?

Also, what is the meaning of 0.0 as the second element of like every single tuple? What is that for?

**Comment by mikahama** [comment]
You can report issues in [https://github.com/giellalt/lang-fin/issues](https://github.com/giellalt/lang-fin/issues)
0.0 is the weight of the analysis, none of the transducers currently have weights, but the functionality is there in case someone decided to implement them.

**Comment by doctorcolossus** [comment]
Thank you for your very quick and informative response, and apologies for my slower one!

As suggested, I have opened [this issue](https://github.com/giellalt/lang-fin/issues/4) at the lang-fin issue tracker.
