### ISSUE TITLE
[BUG] Finnish morphological generation produces empty output in v1.5.1 (and v1.5.0)

### ISSUE THREAD

**Issue by yoge1** [mikahama/uralicNLP#19]
**Describe the bug**
Finnish morphological generation produces empty output in v1.5.1 (and v1.5.0).

**To Reproduce**
1. Run
```
docker run -it --rm python:3.8-slim-buster bash
pip install uralicNLP==1.5.1
python -m uralicNLP.download --languages fin
python
>>> from uralicNLP import uralicApi
>>> uralicApi.generate("käsi+N+Sg+Par", "fin")
```
2. Output:
`[]`

**Expected behavior**
Expected output:
`[['kättä', 0.0]]`

**Desktop (please complete the following information):**
 - OS: Debian 10 (in Docker) / Ubuntu 18.04 (host)
 - Python version: 3.8.17

**Comment by mikahama** [comment]
This issue is related to [pyhfst](https://github.com/Rootroo-ltd/pyhfst). UralicNLP can use several HFST backends, so if you **pip install hfst** or **pip install hfst-dev**, UralicNLP will start using these by default. We are working on a fix for pyhfst, but it requires quite a bit of debugging.

**Comment by mikahama** [comment]
Pyhfst has been fixed
pip install --upgrade pyhfst
