### ISSUE TITLE
Adding Constraint Grammar disambiguation

### ISSUE THREAD

**Issue by nikopartanen** [mikahama/uralicNLP#2]
For several of these languages there are already disambiguation rules which remove most of the readings. Would it be possible somehow to add this into uralicNLP? I have no ideas about the technical problems which may be related to this, but it would make my life million times easier. This would demand sending more than one token at the time, but I assume this would be practical anyway? Thank you for fantastic work!

**Comment by mikahama** [comment]
This is something I have under consideration already... So at some point that will happen

**Comment by mikahama** [comment]
Done
