### ISSUE TITLE
Morphology format in documentation/docstrings

### ISSUE THREAD

**Issue by robaki** [mikahama/uralicNLP#20]
I'm trying to use the constraint grammar disambiguation functionality. While provided explanation and example are helpful, the morphology format is not explained: what are the possible tags? What is their meaning?

The CG3 documentation also lacks this information as well, although I assume that could be because the tags are language specific (?): https://edu.visl.dk/cg3/single/#stream-vislcg

I've analyzed some sentences and found these tags:
```
'<W:0.000000>', '<W:281474976710655.000000>', '<fin>', '?', 
'@+FAUXV', '@+FMAINV', '@-FAUXV', '@-FMAINV', '@<ADVL', 
'@<OBJ', '@<P', '@<PN', '@<SPRED', '@<SUBJ', '@>N', '@>P', 
'@ADVL', '@CNP', '@CVP', '@HAB', '@LOC', '@N<', '@N>', '@NES', 
'@Num<', '@OBJ', '@OBJ>', '@P>', '@PC', '@PCLE', '@SUBJ', 
'@SUBJ>', '@X', 'A', 'ABBR', 'ACR', 'Abe', 'Abl', 'Acc', 'Act', 'Ade', 
'Adv', 'AgPrc', 'All', 'Arab', 'Attr', 'CC', 'CS', 'Card', 'Cmp', 'Cmp/Hyph', 
'Cmpnd', 'Coll', 'Comp', 'ConNeg', 'Cond', 'Dash', 'Dem', 'Der/inen', 
'Der/minen', 'Der/s', 'Der/ttain', 'Digit', 'Ela', 'Err/Orth', 'Ess', 
'Foc/han', 'Foc/ka', 'Foc/kaan', 'Foc/kin', 'Foc/pa', 'Gen', 'Gram/IAbbr', 
'Gram/TAbbr', 'Gram/TNumAbbr', 'Hom1', 'Ill', 'Imprt', 'Ind', 
'Indef', 'Ine', 'InfA', 'InfE', 'InfMa', 'Ins', 'Interj', 'Interr', 'Lat', 'N', 
'Neg', 'NegPrc', 'Nom', 'Num', 'Ord', 'Par', 'Pcle', 'Pe4', 'Pers', 'Pl', 
'Pl1', 'Pl2', 'Pl3', 'Po', 'Pot', 'Pr', 'Pref', 'Pref-', 'PrfPrc', 'Pron', 
'Prop', 'Propn', 'Prs', 'PrsPrc', 'Prt', 'Pss', 'Punct', 'Px3', 'PxPl1', 
'PxPl2', 'PxPl3', 'PxSg1', 'PxSg2', 'PxSg3', 'Qnt', 'Qst', 'Qu', 
'Refl', 'Rel', 'Sem/Curr', 'Sem/Fem', 'Sem/Geo', 'Sem/Geon', 
'Sem/Human', 'Sem/Humann', 'Sem/Org', 'Sg', 'Sg1', 'Sg2', 
'Sg3', 'Superl', 'Tra', 'V', 'VPcle', 'ela', 'gen', 'ill', 'n', 'par', 'sg'
```

While I can guess the meaning of some of them, I'm not exactly sure. I also don't know if this list is complete.

**Comment by rueter** [comment]
Hi,

For the Finnish tag definitions, you should consult the following files:
https://github.com/giellalt/lang-fin/blob/main/src%2Ffst%2Froot.lexc

https://github.com/giellalt/lang-fin/blob/main/src%2Fcg3

Since all of the languages are pretty much parallel, you may want to
consult: sma or sme

Happy New Year's!

Jack Rueter

la 30. jouluk. 2023 klo 20.59 robaki ***@***.***> kirjoitti:

**Comment by robaki** [comment]
Thank you for the links!
I think it would be helpful to add them somewhere in the docs.

Thanks and have a happy new year!

**Comment by mikahama** [comment]
If FST developers ever care to document their transducers, I can link them to UralcNLP documentation
