### ISSUE TITLE
Some morphological tags are missing

### ISSUE THREAD

**Issue by nikopartanen** [mikahama/uralicNLP#5]
I noticed some unexpected behaviour. When I do:

```
from uralicNLP.cg3 import Cg3
cg = Cg3("kpv")
cg.disambiguate(["Ми", "уджалам", "вӧр", "керкаын", "."])
```

I get the result:

```
[('Ми', [<ми - Pron, Pers, Pl1, Nom, <W:0.000000>>]),
 ('уджалам', [<уджавны - V, IV, <W:0.000000>>]),
 ('вӧр',
  [<вӧр - N, Sg, Acc, <W:0.000000>>,
   <вӧр - N, Sg, Nom, <W:0.000000>>,
   <вӧрны - V, IV, <W:0.000000>>]),
 ('керкаын', [<керка - N, Sg, Ine, <W:0.000000>>]),
 ('.', [<. - CLB, <W:0.000000>>])]
```

The problem is that the verb *уджавны* 'to work' has only the tags `V` and `IV`, missing the others for person and tense etc. It seems that all verbs behave this way at the moment.

```
echo "Ми уджалам вӧр керкаын." | hfst-tokenise --giella-cg -W $GTHOME/langs/kpv/tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 -g $GTHOME/langs/kpv/src/syntax/disambiguator.cg3

"<Ми>"
	"ми" Pron Pers Pl1 Nom
: 
"<уджалам>"
	"уджавны" V IV Ind Prs Pl1
: 
"<вӧр>"
	"вӧр" N Sg Acc
	"вӧр" N Sg Nom
: 
"<керкаын>"
	"керка" N Sg Ine
"<.>"
	"." CLB
```

Otherwise everything is working very nicely!

**Comment by mikahama** [comment]
I don't have any control over the FSTs for Komi-Zyrian as they come from the Apertium nightly repository. However, I made sure now that the server has the latest versions of the Apertium transducers. So you could try it out again after running uralicApi.download("kpv")

**Comment by nikopartanen** [comment]
Thanks! This did change the output, but now there are even fewer tags!

```
from uralicNLP.cg3 import Cg3
from uralicNLP import uralicApi
uralicApi.download("kpv")
cg = Cg3("kpv")
cg.disambiguate(["Ми", "уджалам", "вӧр", "керкаын", "."])

Model analyser for kpv was downloaded
Model analyser-norm for kpv was downloaded
Model generator-desc for kpv was downloaded
Model generator-norm for kpv was downloaded
Model generator for kpv was downloaded
Model cg for kpv was downloaded
[('Ми', [<ми - Pron, Pers, Pl1, Nom, <W:0.000000>>]),
 ('уджалам', [<уджавны - V, <W:0.000000>>]),
 ('вӧр',
  [<вӧр - N, Sg, Acc, <W:0.000000>>,
   <вӧр - N, Sg, Nom, <W:0.000000>>,
   <вӧрны - V, <W:0.000000>>]),
 ('керкаын', [<керка - N, Sg, Ine, <W:0.000000>>]),
 ('.', [<. - CLB, <W:0.000000>>])]
```

When I tested the analysers which uralicNLP downloaded they do seem to work normally:

```
echo "уджалам" | hfst-lookup /Users/niko/.uralicNLP/kpv/analyser 
> уджалам	уджавны+V+IV+Ind+Fut+Pl1	0.000000
уджалам	уджавны+V+IV+Ind+Prs+Pl1	0.000000
```

I also tested copying my locally compiled analysers there, but this problem persisted. I haven't seen similar with other languages.

**Comment by mikahama** [comment]
Well,
I just ran uralicApi.download("kpv") and ran your code, and this is what I get

[('Ми', [<ми - Pron, Pers, Pl1, Nom, <W:0.000000>>]), ('уджалам', [<уджавны - V, IV, Ind, Prs, Pl1, <W:0.000000>>]), ('вӧр', [<вӧр - N, Sg, Acc, <W:0.000000>>, <вӧр - N, Sg, Nom, <W:0.000000>>]), ('керкаын', [<керка - N, Sg, Ine, <W:0.000000>>]), ('.', [<. - CLB, <W:0.000000>>])]

So уджалам gets all the tags. Is your uralicNLP up-to-date? 

pip install -U uralicNLP

**Comment by nikopartanen** [comment]
Perfect, now it works! Thanks!
