### ISSUE TITLE
jorgal and giellatekno are the same api

### ISSUE THREAD

**Issue by unhammer** [mikahama/uralicNLP#8]
https://github.com/mikahama/uralicNLP/blob/a89d03fe674bf53d615a58e69463f8f38159b414/uralicNLP/translate.py#L80
doesn't work – there's only one api instance used by both mt-testing and jorgal (http://gtweb.uit.no/apy/)

**Comment by mikahama** [comment]
That used to work as I dug the API urls up myself. If they are nowadays in the same url, maybe its just time to remove the ApertiumJorgalTranslator class altogether...
